# Generated by Django 3.1.4 on 2020-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=150, verbose_name='Ингредиент')),
                ('proteins', models.PositiveSmallIntegerField(default=0, verbose_name='Белки')),
                ('fats', models.PositiveSmallIntegerField(default=0, verbose_name='Жиры')),
                ('carbohydrates', models.PositiveSmallIntegerField(default=0, verbose_name='Углеводы')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
    ]
