# Generated by Django 3.1.4 on 2021-01-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201216_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='recipes.comments', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='recipes.recipe', verbose_name='рецепт'),
        ),
    ]
